### ISSUE TITLE
Fails with exception

### ISSUE THREAD

**Issue by HalfVoxel** [stanfordroboticsclub/fusion360EquationCurve#1]
Hi

I tried to run this, however it seems to fail with an error (shown below)
![screenshot 2018-04-27 10 20 42](https://user-images.githubusercontent.com/1144597/39352377-cf1e17f4-4a04-11e8-9f93-12a277d29fec.png)

Do you have any idea what the cause could be?
I tried to run it in a completely new fusion360 file, both inside and outside sketch mode.

**Comment by HalfVoxel** [comment]
Hmm. Okay. Just commenting that line out (and inserting a required parenthesis) seems to work.

![screenshot 2018-04-27 10 24 13](https://user-images.githubusercontent.com/1144597/39352505-35d24862-4a05-11e8-9a52-18776eb9e1d0.png)

Perhaps this is something that has changed in a new version of fusion 360? I use 2.0.4099.

**Comment by SimonSolar2C** [comment]
Its looking for a ./resources directory which does not exist

**Comment by mikh3x4** [comment]
Fixed

**Comment by SimonSolar2C** [comment]
Tested working - many thanks @mikh3x4
